import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//metadata is reserved key word in Next.js
// The title here is used to formulate the "title" header of Html Root Page in RootLayout
// Description goes to <header> tag
export const metadata = {
  title: "FIRST Next App",
  description: "GENERATED by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
